# Generated by Django 3.0.8 on 2020-08-21 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.TextField()),
                ('content', models.TextField()),
                ('created_time', models.BigIntegerField()),
                ('upvotes', models.PositiveSmallIntegerField()),
                ('downvotes', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.TextField()),
                ('content', models.TextField()),
                ('created_time', models.BigIntegerField()),
                ('upvotes', models.PositiveSmallIntegerField()),
                ('downvotes', models.PositiveSmallIntegerField()),
                ('topic_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chathandler.Topic')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
    ]
