# Generated by Django 3.0.8 on 2020-08-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200826_1858'),
        ('chathandler', '0002_auto_20200827_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='authentication.Group'),
        ),
    ]
