# Generated by Django 3.0.8 on 2020-09-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chathandler', '0004_auto_20200827_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='posted_as_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chathandler.Topic'),
        ),
    ]
