# Generated by Django 3.0.8 on 2020-09-03 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chathandler', '0005_auto_20200902_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='followed_by',
            field=models.ManyToManyField(related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
