# Generated by Django 3.0.8 on 2020-09-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chathandler', '0006_topic_followed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
