# Generated by Django 3.0.8 on 2020-09-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chathandler', '0007_auto_20200903_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_time']},
        ),
    ]
