# Generated by Django 3.0.8 on 2020-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chathandler', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=120)),
                ('unit_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='studentuser',
            name='alias',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='comments_posted',
            field=models.ManyToManyField(to='chathandler.Comment'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='faculty',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='karma',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='topics_posted',
            field=models.ManyToManyField(to='chathandler.Topic'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='university',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='current_units',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='current_units',
            field=models.ManyToManyField(to='authentication.Unit'),
        ),
    ]
