# Generated by Django 3.0.8 on 2020-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200821_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='alias',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
