# Generated by Django 3.0.8 on 2020-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200826_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='current_groups',
            field=models.ManyToManyField(related_name='groups_list', to='authentication.Group'),
        ),
    ]
