# Generated by Django 3.0.8 on 2020-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200826_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='current_groups',
            field=models.ManyToManyField(related_name='student_user', to='authentication.Group'),
        ),
    ]
