# Generated by Django 3.0.8 on 2020-08-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200821_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='current_units',
            field=models.ManyToManyField(related_name='units_list', to='authentication.Unit'),
        ),
    ]
