# Generated by Django 3.0.8 on 2020-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chathandler', '0001_initial'),
        ('authentication', '0004_auto_20200821_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='comments_posted',
            field=models.ManyToManyField(blank=True, to='chathandler.Comment'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='topics_posted',
            field=models.ManyToManyField(blank=True, to='chathandler.Topic'),
        ),
    ]
