# Generated by Django 3.0.8 on 2020-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200902_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveSmallIntegerField()),
                ('comment_id', models.PositiveSmallIntegerField(blank=True)),
                ('action', models.CharField(max_length=120)),
                ('action_time', models.BigIntegerField()),
                ('last_actor', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='studentuser',
            name='notification_history',
            field=models.ManyToManyField(related_name='subscribed_users', to='authentication.NotificationItem'),
        ),
    ]
