# Generated by Django 3.0.8 on 2020-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200821_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='university',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
