# Generated by Django 3.0.8 on 2020-09-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200908_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationitem',
            old_name='action',
            new_name='action_type',
        ),
        migrations.AddField(
            model_name='notificationitem',
            name='action_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
