# Generated by Django 3.0.8 on 2020-09-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200908_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationitem',
            options={'ordering': ['-action_time']},
        ),
    ]
