# Generated by Django 3.0.8 on 2020-09-12 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200909_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationitem',
            name='og_topic_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
